package com.example.sensorlogger.model

import android.location.Location

data class GnssSnapshot(
    val location: Location?,
    val elapsedRealtimeNanos: Long,
    val satellitesVisible: Int,
    val satellitesUsed: Int,
    val cn0Average: Float,
    val cn0Min: Float?,
    val cn0Max: Float?,
    val cn0Percentile25: Float?,
    val cn0Median: Float?,
    val cn0Percentile75: Float?,
    val hasL5: Boolean,
    val hdop: Float,
    val vdop: Float,
    val pdop: Float,
    val provider: String,
    val gnssRawSupported: Boolean,
    val gnssRawCount: Int,
    val gpsVisible: Int,
    val gpsUsed: Int,
    val glonassVisible: Int,
    val glonassUsed: Int,
    val galileoVisible: Int,
    val galileoUsed: Int,
    val beidouVisible: Int,
    val beidouUsed: Int,
    val qzssVisible: Int,
    val qzssUsed: Int,
    val sbasVisible: Int,
    val sbasUsed: Int,
    val rawGpsCount: Int,
    val rawGlonassCount: Int,
    val rawGalileoCount: Int,
    val rawBeidouCount: Int,
    val rawQzssCount: Int,
    val rawSbasCount: Int
) {
    companion object {
        val EMPTY = GnssSnapshot(
            location = null,
            elapsedRealtimeNanos = 0L,
            satellitesVisible = 0,
            satellitesUsed = 0,
            cn0Average = 0f,
            cn0Min = null,
            cn0Max = null,
            cn0Percentile25 = null,
            cn0Median = null,
            cn0Percentile75 = null,
            hasL5 = false,
            hdop = 0f,
            vdop = 0f,
            pdop = 0f,
            provider = "",
            gnssRawSupported = false,
            gnssRawCount = 0,
            gpsVisible = 0,
            gpsUsed = 0,
            glonassVisible = 0,
            glonassUsed = 0,
            galileoVisible = 0,
            galileoUsed = 0,
            beidouVisible = 0,
            beidouUsed = 0,
            qzssVisible = 0,
            qzssUsed = 0,
            sbasVisible = 0,
            sbasUsed = 0,
            rawGpsCount = 0,
            rawGlonassCount = 0,
            rawGalileoCount = 0,
            rawBeidouCount = 0,
            rawQzssCount = 0,
            rawSbasCount = 0
        )
    }
}
