package com.example.sensorlogger.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class TelemetryPayloadV11(
    @SerialName("schema.version") val schemaVersion: String = SCHEMA_VERSION,
    @SerialName("device.id") val deviceId: String,
    @SerialName("operator.id") val operatorId: String,
    @SerialName("equipment.tag") val equipmentTag: String? = null,
    @SerialName("seq_id") val sequenceId: Long,
    @SerialName("ts_epoch") val timestampEpoch: Long,
    @SerialName("gnss.elapsedRealtimeNanos") val gnssElapsedRealtimeNanos: Long? = null,

    @SerialName("gnss.fix") val gnssFix: String? = null,
    @SerialName("gnss.lat") val latitude: Float? = null,
    @SerialName("gnss.lon") val longitude: Float? = null,
    @SerialName("gnss.alt") val altitude: Float? = null,
    @SerialName("gnss.speed") val speed: Float? = null,
    @SerialName("gnss.course") val course: Float? = null,
    @SerialName("gnss.hdop") val hdop: Float? = null,
    @SerialName("gnss.vdop") val vdop: Float? = null,
    @SerialName("gnss.pdop") val pdop: Float? = null,
    @SerialName("gnss.num_sats") val satellitesUsed: Int? = null,
    @SerialName("gnss.cn0_avg") val cn0Average: Float? = null,
    @SerialName("gnss.accuracy_m") val accuracyMeters: Float? = null,
    @SerialName("gnss.provider") val provider: String? = null,
    @SerialName("gnss.vert_accuracy_m") val verticalAccuracyMeters: Float? = null,
    @SerialName("gnss.speed_accuracy_mps") val speedAccuracyMps: Float? = null,
    @SerialName("gnss.bearing_accuracy_deg") val bearingAccuracyDeg: Float? = null,
    @SerialName("gnss.sats_visible") val satellitesVisible: Int? = null,
    @SerialName("gnss.has_l5") val hasL5: Boolean? = null,
    @SerialName("gnss.raw_supported") val gnssRawSupported: Boolean? = null,
    @SerialName("gnss.raw_count") val gnssRawCount: Int? = null,
    @SerialName("gnss.cn0.min") val cn0Min: Float? = null,
    @SerialName("gnss.cn0.max") val cn0Max: Float? = null,
    @SerialName("gnss.cn0.p25") val cn0Percentile25: Float? = null,
    @SerialName("gnss.cn0.p50") val cn0Median: Float? = null,
    @SerialName("gnss.cn0.p75") val cn0Percentile75: Float? = null,
    @SerialName("gnss.constellation.gps_visible") val gpsVisible: Int? = null,
    @SerialName("gnss.constellation.gps_used") val gpsUsed: Int? = null,
    @SerialName("gnss.constellation.glonass_visible") val glonassVisible: Int? = null,
    @SerialName("gnss.constellation.glonass_used") val glonassUsed: Int? = null,
    @SerialName("gnss.constellation.galileo_visible") val galileoVisible: Int? = null,
    @SerialName("gnss.constellation.galileo_used") val galileoUsed: Int? = null,
    @SerialName("gnss.constellation.beidou_visible") val beidouVisible: Int? = null,
    @SerialName("gnss.constellation.beidou_used") val beidouUsed: Int? = null,
    @SerialName("gnss.constellation.qzss_visible") val qzssVisible: Int? = null,
    @SerialName("gnss.constellation.qzss_used") val qzssUsed: Int? = null,
    @SerialName("gnss.constellation.sbas_visible") val sbasVisible: Int? = null,
    @SerialName("gnss.constellation.sbas_used") val sbasUsed: Int? = null,
    @SerialName("gnss.raw.gps_count") val rawGpsCount: Int? = null,
    @SerialName("gnss.raw.glonass_count") val rawGlonassCount: Int? = null,
    @SerialName("gnss.raw.galileo_count") val rawGalileoCount: Int? = null,
    @SerialName("gnss.raw.beidou_count") val rawBeidouCount: Int? = null,
    @SerialName("gnss.raw.qzss_count") val rawQzssCount: Int? = null,
    @SerialName("gnss.raw.sbas_count") val rawSbasCount: Int? = null,

    @SerialName("baro.pressure_hpa") val baroPressureHpa: Float? = null,
    @SerialName("baro.altitude_m") val baroAltitudeMeters: Float? = null,

    @SerialName("imu.acc.norm.rms") val accNormRms: Float? = null,
    @SerialName("imu.acc.norm.sigma") val accNormSigma: Float? = null,
    @SerialName("imu.jerk.norm.rms") val jerkNormRms: Float? = null,
    @SerialName("imu.jerk.norm.sigma") val jerkNormSigma: Float? = null,
    @SerialName("imu.gyro.norm.rms") val gyroNormRms: Float? = null,
    @SerialName("imu.gyro.norm.sigma") val gyroNormSigma: Float? = null,
    @SerialName("imu.yaw_rate.deg_s") val yawRateDegPerSec: Float? = null,
    @SerialName("imu.samples") val imuSamples: Int? = null,
    @SerialName("imu.fps_eff") val imuFpsEffective: Float? = null,

    @SerialName("imu.acc.x.mean") val accXMean: Float? = null,
    @SerialName("imu.acc.x.rms") val accXRms: Float? = null,
    @SerialName("imu.acc.x.min") val accXMin: Float? = null,
    @SerialName("imu.acc.x.max") val accXMax: Float? = null,
    @SerialName("imu.acc.x.sigma") val accXSigma: Float? = null,
    @SerialName("imu.acc.y.mean") val accYMean: Float? = null,
    @SerialName("imu.acc.y.rms") val accYRms: Float? = null,
    @SerialName("imu.acc.y.min") val accYMin: Float? = null,
    @SerialName("imu.acc.y.max") val accYMax: Float? = null,
    @SerialName("imu.acc.y.sigma") val accYSigma: Float? = null,
    @SerialName("imu.acc.z.mean") val accZMean: Float? = null,
    @SerialName("imu.acc.z.rms") val accZRms: Float? = null,
    @SerialName("imu.acc.z.min") val accZMin: Float? = null,
    @SerialName("imu.acc.z.max") val accZMax: Float? = null,
    @SerialName("imu.acc.z.sigma") val accZSigma: Float? = null,

    @SerialName("imu.jerk.x.rms") val jerkXRms: Float? = null,
    @SerialName("imu.jerk.y.rms") val jerkYRms: Float? = null,
    @SerialName("imu.jerk.z.rms") val jerkZRms: Float? = null,

    @SerialName("imu.gyro.x.mean") val gyroXMean: Float? = null,
    @SerialName("imu.gyro.x.rms") val gyroXRms: Float? = null,
    @SerialName("imu.gyro.x.min") val gyroXMin: Float? = null,
    @SerialName("imu.gyro.x.max") val gyroXMax: Float? = null,
    @SerialName("imu.gyro.x.sigma") val gyroXSigma: Float? = null,
    @SerialName("imu.gyro.y.mean") val gyroYMean: Float? = null,
    @SerialName("imu.gyro.y.rms") val gyroYRms: Float? = null,
    @SerialName("imu.gyro.y.min") val gyroYMin: Float? = null,
    @SerialName("imu.gyro.y.max") val gyroYMax: Float? = null,
    @SerialName("imu.gyro.y.sigma") val gyroYSigma: Float? = null,
    @SerialName("imu.gyro.z.mean") val gyroZMean: Float? = null,
    @SerialName("imu.gyro.z.rms") val gyroZRms: Float? = null,
    @SerialName("imu.gyro.z.min") val gyroZMin: Float? = null,
    @SerialName("imu.gyro.z.max") val gyroZMax: Float? = null,
    @SerialName("imu.gyro.z.sigma") val gyroZSigma: Float? = null,

    @SerialName("imu.pitch_deg") val pitchDeg: Float? = null,
    @SerialName("imu.roll_deg") val rollDeg: Float? = null,
    @SerialName("imu.yaw_deg") val yawDeg: Float? = null,
    @SerialName("imu.q.w") val quaternionW: Float? = null,
    @SerialName("imu.q.x") val quaternionX: Float? = null,
    @SerialName("imu.q.y") val quaternionY: Float? = null,
    @SerialName("imu.q.z") val quaternionZ: Float? = null,
    @SerialName("imu.acc.accuracy") val accelerometerAccuracy: String? = null,
    @SerialName("imu.gyro.accuracy") val gyroscopeAccuracy: String? = null,
    @SerialName("imu.rotation.accuracy") val rotationAccuracy: String? = null,
    @SerialName("imu.motion.stationary") val motionStationary: Boolean? = null,
    @SerialName("imu.motion.shock_level") val motionShockLevel: String? = null,
    @SerialName("imu.motion.shock_score") val motionShockScore: Float? = null,

    @SerialName("imu.linear_acc.norm.rms") val linearAccNormRms: Float? = null,
    @SerialName("imu.linear_acc.norm.sigma") val linearAccNormSigma: Float? = null,
    @SerialName("imu.linear_acc.x.mean") val linearAccXMean: Float? = null,
    @SerialName("imu.linear_acc.x.rms") val linearAccXRms: Float? = null,
    @SerialName("imu.linear_acc.x.min") val linearAccXMin: Float? = null,
    @SerialName("imu.linear_acc.x.max") val linearAccXMax: Float? = null,
    @SerialName("imu.linear_acc.x.sigma") val linearAccXSigma: Float? = null,
    @SerialName("imu.linear_acc.y.mean") val linearAccYMean: Float? = null,
    @SerialName("imu.linear_acc.y.rms") val linearAccYRms: Float? = null,
    @SerialName("imu.linear_acc.y.min") val linearAccYMin: Float? = null,
    @SerialName("imu.linear_acc.y.max") val linearAccYMax: Float? = null,
    @SerialName("imu.linear_acc.y.sigma") val linearAccYSigma: Float? = null,
    @SerialName("imu.linear_acc.z.mean") val linearAccZMean: Float? = null,
    @SerialName("imu.linear_acc.z.rms") val linearAccZRms: Float? = null,
    @SerialName("imu.linear_acc.z.min") val linearAccZMin: Float? = null,
    @SerialName("imu.linear_acc.z.max") val linearAccZMax: Float? = null,
    @SerialName("imu.linear_acc.z.sigma") val linearAccZSigma: Float? = null,

    @SerialName("imu.mag.x.mean") val magnetometerXMean: Float? = null,
    @SerialName("imu.mag.x.rms") val magnetometerXRms: Float? = null,
    @SerialName("imu.mag.x.min") val magnetometerXMin: Float? = null,
    @SerialName("imu.mag.x.max") val magnetometerXMax: Float? = null,
    @SerialName("imu.mag.x.sigma") val magnetometerXSigma: Float? = null,
    @SerialName("imu.mag.y.mean") val magnetometerYMean: Float? = null,
    @SerialName("imu.mag.y.rms") val magnetometerYRms: Float? = null,
    @SerialName("imu.mag.y.min") val magnetometerYMin: Float? = null,
    @SerialName("imu.mag.y.max") val magnetometerYMax: Float? = null,
    @SerialName("imu.mag.y.sigma") val magnetometerYSigma: Float? = null,
    @SerialName("imu.mag.z.mean") val magnetometerZMean: Float? = null,
    @SerialName("imu.mag.z.rms") val magnetometerZRms: Float? = null,
    @SerialName("imu.mag.z.min") val magnetometerZMin: Float? = null,
    @SerialName("imu.mag.z.max") val magnetometerZMax: Float? = null,
    @SerialName("imu.mag.z.sigma") val magnetometerZSigma: Float? = null,
    @SerialName("imu.mag.field_strength_uT") val magnetometerFieldStrength: Float? = null
) {
    companion object {
        const val SCHEMA_VERSION = "1.2.0"

        val CSV_HEADER: List<String> = listOf(
            "schema.version",
            "device.id",
            "operator.id",
            "equipment.tag",
            "seq_id",
            "ts_epoch",
            "gnss.elapsedRealtimeNanos",
            "gnss.fix",
            "gnss.lat",
            "gnss.lon",
            "gnss.alt",
            "gnss.speed",
            "gnss.course",
            "gnss.hdop",
            "gnss.vdop",
            "gnss.pdop",
            "gnss.num_sats",
            "gnss.cn0_avg",
            "gnss.accuracy_m",
            "gnss.provider",
            "gnss.vert_accuracy_m",
            "gnss.speed_accuracy_mps",
            "gnss.bearing_accuracy_deg",
            "gnss.sats_visible",
            "gnss.has_l5",
            "gnss.raw_supported",
            "gnss.raw_count",
            "gnss.cn0.min",
            "gnss.cn0.max",
            "gnss.cn0.p25",
            "gnss.cn0.p50",
            "gnss.cn0.p75",
            "gnss.constellation.gps_visible",
            "gnss.constellation.gps_used",
            "gnss.constellation.glonass_visible",
            "gnss.constellation.glonass_used",
            "gnss.constellation.galileo_visible",
            "gnss.constellation.galileo_used",
            "gnss.constellation.beidou_visible",
            "gnss.constellation.beidou_used",
            "gnss.constellation.qzss_visible",
            "gnss.constellation.qzss_used",
            "gnss.constellation.sbas_visible",
            "gnss.constellation.sbas_used",
            "gnss.raw.gps_count",
            "gnss.raw.glonass_count",
            "gnss.raw.galileo_count",
            "gnss.raw.beidou_count",
            "gnss.raw.qzss_count",
            "gnss.raw.sbas_count",
            "baro.pressure_hpa",
            "baro.altitude_m",
            "imu.acc.norm.rms",
            "imu.acc.norm.sigma",
            "imu.jerk.norm.rms",
            "imu.jerk.norm.sigma",
            "imu.gyro.norm.rms",
            "imu.gyro.norm.sigma",
            "imu.yaw_rate.deg_s",
            "imu.samples",
            "imu.fps_eff",
            "imu.acc.x.mean",
            "imu.acc.x.rms",
            "imu.acc.x.min",
            "imu.acc.x.max",
            "imu.acc.x.sigma",
            "imu.acc.y.mean",
            "imu.acc.y.rms",
            "imu.acc.y.min",
            "imu.acc.y.max",
            "imu.acc.y.sigma",
            "imu.acc.z.mean",
            "imu.acc.z.rms",
            "imu.acc.z.min",
            "imu.acc.z.max",
            "imu.acc.z.sigma",
            "imu.jerk.x.rms",
            "imu.jerk.y.rms",
            "imu.jerk.z.rms",
            "imu.gyro.x.mean",
            "imu.gyro.x.rms",
            "imu.gyro.x.min",
            "imu.gyro.x.max",
            "imu.gyro.x.sigma",
            "imu.gyro.y.mean",
            "imu.gyro.y.rms",
            "imu.gyro.y.min",
            "imu.gyro.y.max",
            "imu.gyro.y.sigma",
            "imu.gyro.z.mean",
            "imu.gyro.z.rms",
            "imu.gyro.z.min",
            "imu.gyro.z.max",
            "imu.gyro.z.sigma",
            "imu.pitch_deg",
            "imu.roll_deg",
            "imu.yaw_deg",
            "imu.q.w",
            "imu.q.x",
            "imu.q.y",
            "imu.q.z",
            "imu.acc.accuracy",
            "imu.gyro.accuracy",
            "imu.rotation.accuracy",
            "imu.motion.stationary",
            "imu.motion.shock_level",
            "imu.motion.shock_score",
            "imu.linear_acc.norm.rms",
            "imu.linear_acc.norm.sigma",
            "imu.linear_acc.x.mean",
            "imu.linear_acc.x.rms",
            "imu.linear_acc.x.min",
            "imu.linear_acc.x.max",
            "imu.linear_acc.x.sigma",
            "imu.linear_acc.y.mean",
            "imu.linear_acc.y.rms",
            "imu.linear_acc.y.min",
            "imu.linear_acc.y.max",
            "imu.linear_acc.y.sigma",
            "imu.linear_acc.z.mean",
            "imu.linear_acc.z.rms",
            "imu.linear_acc.z.min",
            "imu.linear_acc.z.max",
            "imu.linear_acc.z.sigma",
            "imu.mag.x.mean",
            "imu.mag.x.rms",
            "imu.mag.x.min",
            "imu.mag.x.max",
            "imu.mag.x.sigma",
            "imu.mag.y.mean",
            "imu.mag.y.rms",
            "imu.mag.y.min",
            "imu.mag.y.max",
            "imu.mag.y.sigma",
            "imu.mag.z.mean",
            "imu.mag.z.rms",
            "imu.mag.z.min",
            "imu.mag.z.max",
            "imu.mag.z.sigma",
            "imu.mag.field_strength_uT"
        )
    }
}
